version: "3.9"

services:

  pdf-microservice:
    ports:
      - "8080:8080"
    build:
      dockerfile: Dockerfile
    image: pdf-microservice
    container_name: pdf_microservice
    restart: unless-stopped
    networks:
      - app-net
networks:
  app-net:
    driver: bridge