[api]
host = "localhost"
port = "8080"
local_save = false

[s3]
access_key_id = "YOUR_ACCESS_KEY"
secret_access_key = "YOUR_SECRET_KEY"
use_ssl = false
bucket_name = "your-bucket"
region = "RU"
endpoint        = "https://s3.timeweb.com"
file_path        = "path/to/your/file.pdf"
object_key       = "file.pdf"